name: Capstone Group 2 - Penerapan CI/CD API User

on:
  push:
    branches:
      - master
      - Penerapan_CICD_API
  pull_request:
    branches:
      - master
      - Penerapan_CICD_API

jobs:
  build:
    name : Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots clean install -DskipTests
  test:
    name: TEST API USER - AUTOMATION
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name : Test API
        run : mvn clean verify